### ISSUE TITLE
::malloc has not been declared

### ISSUE THREAD

**Issue by TurkeyMan** [aras-p/hlsl2glslfork#44]
I'm getting this strange error "::malloc has not been declared" when I try and build for linux x64.

The problem is described here: http://nerdland.net/unstumping-the-internet/malloc-has-not-been-declared/
But this project uses cmake rather than autoconf.
What needs to be done to fix it?

**Comment by computerquip** [comment]
Does this problem still persist?

**Comment by aras-p** [comment]
Possibly fixed already.
