### ISSUE TITLE
Compiling on linux?

### ISSUE THREAD

**Issue by TurkeyMan** [aras-p/hlsl2glslfork#45]
Has anyone tried building on linux recently?
I had to `#include <cstdlib> and <cstring>` to glslCommon.cpp.

Now I'm having an error in Linux/ossource.cpp:
First it tries to `#include "InitializeDll.h"`, which I comment out. Then `error: ‘DetachThread’ was not declared in this scope`

The code:
```
void DetachThreadLinux(void *)
{
	DetachThread();
}
```
Doesn't look right. Maybe `pthread_detach()`, but what argument?
I went with: `pthread_detach(pthread_self());`, but now I'm just making stuff up.
I got a lib. Can't yet test if it works for other reasons, but I suggest someone try building linux and make sure it works at git head.

**Comment by computerquip** [comment]
Is there any reason to keep this issue open?
