### ISSUE TITLE
-fPIC on linux x86_64?

### ISSUE THREAD

**Issue by TurkeyMan** [aras-p/hlsl2glslfork#46]
I can't work out how to build with -fPIC. I've tried everything I can think of, verbose output shows the flag passed to the compiler, still doesn't seem to work...
Either way, -fPIC is basically a requirement for x64 libs. Consider adding it by default? Otherwise many users will repeat this headache.

**Comment by computerquip** [comment]
hlsl2glslfork appears to build fine for my native environment (amd64). Does this problem still persist?
