### ISSUE TITLE
Is the description accurate? 

### ISSUE THREAD

**Issue by computerquip** [aras-p/hlsl2glslfork#65]
I'm using this tool because it's the only active project for translating HLSL source to GLSL source (oh the torment...). The description slightly scares me as to whether I should invest time into the tool. 

>The library is not currently thread-safe. 

This isn't specific enough. Not that this should probably be run in a threaded environment too often... but calling construct compiler and shipping the compiler off in a thread to Hlsl2Glsl_Parse and Hlsl2Glsl_Translate seems like an optimal route, especially if we have a few hundred shaders that are large. Can this be improved?

>Support for DX11 features might or might not get added due to the bad condition the original code is in (very obscure and inefficient), instead maybe a new cross-compiler will be made. Someday. Maybe.

Is this really the case? Is the code that bad? If so, should I look into making new tools? How is the translation done? Is there an IR format hlsl2glsl uses? There's a lot of things that aren't very clear that I think would be good to document so I don't spend weeks looking into the features/capabilities/potential of the codebase.

**Comment by aras-p** [comment]
> shipping the compiler off in a thread to Hlsl2Glsl_Parse and Hlsl2Glsl_Translate seems like an optimal route

Yes, making it thread safe "should be easy", but at least a while ago the preprocessor itself was not thread safe (used a lot of global variables etc.). That said, these days the preprocessor is based on MojoShader's one, which I think is thread safe.

We (at Unity) don't use this from multiple threads at once; we run multiple shader compiler processes instead. Largely because some other closed source shader compilers aren't thread safe either. So I probably won't have time to make this thread safe myself, but PRs are welcome :)

**Comment by aras-p** [comment]
> Is the code that bad?

I think the code is quite bad, yeah. I don't quite understand the data flows, or the allocation patterns.

> If so, should I look into making new tools?

I'm hoping that someday the world will have, for example, a clang-based HLSL compiler that would compile to SPIR-V; and then SPIR-V can be translated into anything else (GLSL, MetalSL etc.). Another though I had, was to build a HLSL parser for glsl-optimizer (which is basically Mesa's GLSL parser/optimizer/IR). I think any of these approaches is better than trying to evolve hlsl2glsl codebase frankly. Alas, did not have time to do either of them.

> How is the translation done? Is there an IR format hlsl2glsl uses?

Flex lexer, Bison parser, that parses into some sort of AST/IR.

> There's a lot of things that aren't very clear that I think would be good to document

Indeed! A lot of things aren't clear to me either :)
