### ISSUE TITLE
Howto section on README.md

### ISSUE THREAD

**Issue by MarianoGnu** [aras-p/hlsl2glslfork#75]
it would be nice to know how to use this library on Unity, i can figure it out how to link the library in a c++ project and use it correctly, but have not idea of how to link c++ static libraries to a Unity project.

**Comment by aras-p** [comment]
Not sure how that relates to Unity. Unity itself uses this library internally (so when you write shaders in unity, and they need to be compiled for OpenGL ES 2.0 or Metal or legacy desktop GL2, this is used). You don't have to do anything.

What do you want to achieve?

**Comment by MarianoGnu** [comment]
Get a readable translation to use on other apps

**Comment by aras-p** [comment]
I'm still not sure what should be improved. A tutorial in how to use it?

**Comment by MarianoGnu** [comment]
I want a way to input string and get an string back, that's all, i dont want the shader to compile or render anything.
