### ISSUE TITLE
CMake Cannot Find main.cpp in `hlslang/OSDependent/Windows` During Generating

### ISSUE THREAD

**Issue by SirHoog** [aras-p/hlsl2glslfork#82]
**(This is my first GitHub issue, so I apologize if I'm not specific enough or if this is a dumb question 😅)**

I am trying to build this project, not for Unity, but for the Ogre engine.

I am using Windows, CMake, and Visual Studio 2022 (Community).

When I try generating with CMake with `cmake -G "Visual Studio 17 2022" -A x64 ..` it returns:
```
...

-- Configuring done (6.7s)
CMake Error at CMakeLists.txt:202 (add_library):
  Cannot find source file:

    hlslang/OSDependent/Windows/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:202 (add_library):
  No SOURCES given to target: hlsl2glsl

...
```

I tried searching for a `main.cpp` anywhere in the project, but I didn't find one. Is it missing or is the CMakeLists.txt referring to the wrong file?

Is something missing or did I do something wrong?

**Comment by aras-p** [comment]
As the readme says, "Some people have contributed CMake build scripts, but I am not maintaining them" -- and I guess cmake indeed does not actually work. Can you use the Visual Studio or Xcode project instead?

**Comment by SirHoog** [comment]
It turns out I'm just stupid and I tried building Ogre myself when I could literally just download the MSVC SDK instead and it works just fine. I appreciate your response, though. Very sorry for taking your time😅😬.
